name: brimlet
description: A Simple Banking App

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  firebase_auth: null
  firebase_core: null
  flutter:
    sdk: flutter
  flutter_bloc: null
  local_auth: ^2.1.0
  provider: null

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
